/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IdRegistry__factory } from "./IdRegistry__factory";
export { NameRegistry__factory } from "./NameRegistry__factory";
